**1. What is parameter?**

Ans- In Machine Learning, a parameter is a configuration value that a model learns from the data during training. These values determine how the model makes predictions or classifications based on input data.


   example:-   y = mx+c    where m and c are parameters




**2. (a)What is correlation?**

**(b)what does negative correlation mean?**

Ans - correlation measures how strongly two variables are related. A positive correlation means they increase together, while a negative correlation means one decreases as the other increases. Examples-

1.   Alcohol consumption increases, No. of year to live decrease.
2.   Area of house increases, price of house aslo increases.

**3. Define Machine Learning. What are the main components in Machine Learning?**

Ans - Machine Learning is a method where systems learn from data to make predictions or decisions without explicit programming.
   Main components are:-

1.  Data - Input information.
2.  Model - Algorithm for predictions.
3.  Features - Relevant input variables.
4.  Training - Learning from data.
5.  Evaluation - Testing performance.
7.  Prediction - Generating outputs.











**4. How does loss value help in determining whether the model is good or not?**

Ans - The loss value measures how far the model's predictions are from the actual values.


*   Low loss: Model predictions are close to the actual values, meaning it's performing well.
*   High loss: Model predictions are inaccurate, indicating poor performance.


**5. What are continuous and categorical variables?**

Ans - Continuous variables are numeric and can take any value within a range. They are measured and can have decimal points. example - height, weight.

 Categorical variables represent categories or labels and have distinct, non-numeric values. example - Gender, colour.


**6. How do we handle categorical variables in Machine Learning? What are the common techniques?**

Ans - To handle categorical variables in Machine Learning:
*   One-Hot Encoding: Creates binary columns for each category.
*   Label Encoding: Converts categories into unique integers.
*   Ordinal Encoding: Assigns numbers to ordered categories.
*   Target Encoding: Replaces categories with the target variable's mean.

**7. What do you mean by training and testing a dataset?**

Ans - Training: Teaching the model using a portion of the data.

Testing: Evaluating the model's performance on unseen data.

**8. What is sklearn.preprocessing?**

Ans - sklearn.preprocessing helps prepare data for machine learning by scaling, transforming, and encoding it. Key functions include:
*   StandardScaler: Standardizes features.
*   MinMaxScaler: Scales features to a range.
*   OneHotEncoder: Encodes categorical variables.
*   LabelEncoder: Converts labels to numbers.

**9. What is a Test set?**

Ans - A test set is a portion of the dataset that is used to evaluate the performance of a machine learning model after it has been trained. The test set contains data the model hasn't seen during training, helping assess how well the model generalizes to new, unseen data.

**10. How do we split data for model fitting (training and testing) in Python?**

In [ ]:
# we can split data for model fitting using train_test_split from sklearn.model_selection
from sklearn.model_selection import train_test_split

# Example dataset
X = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]  # Features
y = [0, 1, 0, 1, 0]  # Labels

# Split data into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)


X_train: [[9, 10], [5, 6], [1, 2], [7, 8]]
X_test: [[3, 4]]
y_train: [0, 0, 0, 1]
y_test: [1]


**How do you approach a Machine Learning problem?**

Ans - To approach a Machine Learning problem:

*   Define the Problem: Understand the goal.
*   Collect and Prepare Data: Clean and preprocess the data.
*   Split the Data: Divide into training and testing sets.
*   Choose a Model: Select the appropriate algorithm.
*   Train the Model: Fit the model on the training data.
*   Evaluate the Model: Test the model's performance.
*   Tune the Model: Optimize hyperparameters.
*   Deploy the Model: Use it in real-world applications
*   Monitor and Improve: Continuously update the model.

**11. Why do we have to perform EDA before fitting a model to the data?**

Ans - EDA is important before fitting a model because it helps understand the data, detect issues like missing values or outliers, select relevant features, and decide on necessary data transformations. It also guides choosing the right model, leading to better performance and more accurate predictions.

**12. What is correlation?**

Ans - correlation measures how strongly two variables are related. A positive correlation means they increase together, while a negative correlation means one decreases as the other increases.

**13. what does negative correlation mean?**

Ans - A negative correlation means one variable decreases as the other variable increases.
   example - As speed of car increases time taken to reach destination decreases




**14. How can you find correlation between variables in Python?**

In [ ]:
import pandas as pd

# Example dataset
data = {
    'Feature1': [1, 2, 3, 4, 5],
    'Feature2': [5, 4, 3, 2, 1],
    'Feature3': [1, 3, 2, 4, 5]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Calculate the correlation between features
correlation_matrix = df.corr()

print(correlation_matrix)


          Feature1  Feature2  Feature3
Feature1       1.0      -1.0       0.9
Feature2      -1.0       1.0      -0.9
Feature3       0.9      -0.9       1.0


**15. What is causation? Explain difference between correlation and causation with an example.**

Ans - Causation means one variable directly causes another.

Correlation means two variables are related but one doesn't necessarily cause the other.

Example: Ice cream sales and drowning are correlated in summer but ice cream doesn't cause drowning. Smoking causes lung cancer.

**16. What is an Optimizer? What are different types of optimizers? Explain each with an example.**

Ans - An optimizer in machine learning is an algorithm that adjusts the model's parameters to minimize the loss function, helping the model learn and make accurate predictions.

*   Gradient Descent: Updates parameters by moving in the direction of the steepest descent. e.g -  In linear regression, it adjusts the slope and intercept to minimize the error between predicted and actual values.  
*   Stochastic Gradient Descent (SGD): Updates after each data point, faster but noisier. e.g - Used in training deep learning models with large datasets, where each update is based on a single data point.
*   Mini-Batch Gradient Descent: Uses a small batch of data for updates, balancing speed and stability. e.g - Commonly used in neural networks to speed up training without too much noise.
*   Adam: Combines gradient descent with momentum for faster, more efficient convergence. e.g - Frequently used in deep learning, as it combines the benefits of SGD and momentum, making it effective for large datasets.
*   RMSprop: Adjusts learning rate based on recent gradients, useful for noisy data. e.g -  Often used in recurrent neural networks (RNNs) or when training models on time-series data.

**17. What is sklearn.linear_model ?**

Ans - sklearn.linear_model is a module in Scikit-learn that provides linear models for machine learning. These models are used for tasks like regression and classification.

**18. What does model.fit() do? What arguments must be given?**

Ans - The model.fit() function in machine learning is used to train a model using the training data.

It fits the model to the training data by adjusting its parameters (like weights) to minimize the error or loss function.

In [1]:
# Arguments :- X: The training features (input data).
# y: The training labels (target/output values)

from sklearn.linear_model import LinearRegression

# Example data
X_train = [[1], [2], [3], [4]]
y_train = [1, 2, 3, 4]

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)


LinearRegression()

**19. What does model.predict() do? What arguments must be given?**

In [4]:
# model.predict() is used to make predictions on new data after the model is trained.
from sklearn.linear_model import LinearRegression

# Example data
X_train = [[1], [2], [3], [4]]
y_train = [1, 2, 3, 4]

# Train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on new data
X_new = [[5], [6]]
predictions = model.predict(X_new)

print(predictions)


[5. 6.]


**20. What are continuous and categorical variables?**

Ans - Continuous variables are numeric and can take any value within a range. They are measured and can have decimal points. example - height, weight.

 Categorical variables represent categories or labels and have distinct, non-numeric values. example - Gender, colour.


**21. What is feature scaling? How does it help in Machine Learning?**

Ans - Feature scaling is the process of normalizing or standardizing the range of features (input data) so that they are on a similar scale.

It helps by:
*   Improving convergence in algorithms (e.g., gradient descent).
*   Preventing features with larger values from dominating the model.

**22. How do we perform scaling in Python**

In [7]:
# we can perform scaling using the StandardScaler or MinMaxScaler from sklearn.preprocessing.
from sklearn.preprocessing import StandardScaler

# Example data
X_train = [[1, 2], [3, 4], [5, 6]]

# Initialize and fit the scaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(X_train)

print(scaled_data)


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [8]:
from sklearn.preprocessing import MinMaxScaler

# Example data
X_train = [[1, 2], [3, 4], [5, 6]]

# Initialize and fit the scaler
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(X_train)

print(scaled_data)


[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


**23. What is sklearn.preprocessing?**

Ans - sklearn.preprocessing helps prepare data for machine learning by scaling, transforming, and encoding it. Key functions include:
*   StandardScaler: Standardizes features.
*   MinMaxScaler: Scales features to a range.
*   OneHotEncoder: Encodes categorical variables.
*   LabelEncoder: Converts labels to numbers.

**24. How do we split data for model fitting (training and testing) in Python?**

In [9]:
# we can split data for model fitting using train_test_split from sklearn.model_selection
from sklearn.model_selection import train_test_split

# Example dataset
X = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]  # Features
y = [0, 1, 0, 1, 0]  # Labels

# Split data into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)


X_train: [[9, 10], [5, 6], [1, 2], [7, 8]]
X_test: [[3, 4]]
y_train: [0, 0, 0, 1]
y_test: [1]


**25. Explain data encoding?**

Ans - Data encoding is the process of converting categorical data (non-numeric) into a numeric format that machine learning models can understand. common types of Encoding are Label Encoding and One- Hot Encoding.

In [11]:
#Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
encoded_data = le.fit_transform(['cat', 'dog', 'cat', 'bird'])
print(encoded_data)


[1 2 1 0]


In [16]:
# One- Hot Encoding
from sklearn.preprocessing import OneHotEncoder
import numpy as np
data = np.array([['cat'], ['dog'], ['cat'], ['bird']])

# Initialize the encoder and fit/transform
encoder = OneHotEncoder(sparse_output=False)
encoded_data = encoder.fit_transform(data)

print(encoded_data)


[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
